services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hexagonal
      POSTGRES_PASSWORD: hexagonal_local
      POSTGRES_DB: hexagonal_bank
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  pgdata:
