services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cqrs_es
      POSTGRES_PASSWORD: cqrs_es_local
      POSTGRES_DB: cqrs_es_bank
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  pgdata:
